# Generated by Django 4.2 on 2023-05-18 05:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='default_image',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='userImage/default_profilePic.png', max_length=255, verbose_name='profile_picture/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_cover_image',
            field=models.ImageField(default='userCover/default_cover.png', upload_to='', verbose_name='cover_picture'),
        ),
    ]
