# Generated by Django 4.2 on 2023-05-18 05:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_user_default_image_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_cover_image',
            field=cloudinary.models.CloudinaryField(default='cover_picture/bu9dardzvvzaywvphjs7.jpg', max_length=255, verbose_name='cover_picture/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='profile_picture/vmfvz95l1n1gge6amqt5.png', max_length=255, verbose_name='profile_picture/'),
        ),
    ]
