# Generated by Django 4.2 on 2023-05-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likeCount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
