# Generated by Django 4.2 on 2023-06-09 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_user_cover_picture_alter_user_profile_picture'),
        ('posts', '0009_post_report_count_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemovedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed_at', models.DateTimeField(auto_now_add=True)),
                ('removed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removed_by', to='user.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
